version: "3.8"

services:
  app:
    image: grails-docker:latest
    ports:
      - "8080:8080"
      - "8000:8000"
    networks:
      - grails-docker-network
networks:
  grails-docker-network:
    driver: bridge